### ISSUE TITLE
Support for multiple version constraints

### ISSUE THREAD

**Issue by iggy** [patrickjahns/dependabot-terraform-action#40]
Currently this action fails when it encounters versions like this `version = "~> 13, <14"` which should be supported based on the terraform [docs](https://www.terraform.io/docs/language/expressions/version-constraints.html#version-constraint-syntax).

The full error from the run output 

```text
bundler: failed to load command: ./dependabot.rb (./dependabot.rb)
41
Gem::Requirement::BadRequirementError: Illformed requirement ["~> 13, <14"]
42
  /usr/local/bundle/bundler/gems/dependabot-core-44f458dba8ce/terraform/lib/dependabot/terraform/requirement.rb:15:in `parse'
43
  /usr/local/lib/ruby/2.6.0/rubygems/requirement.rb:135:in `block in initialize'
44
  /usr/local/lib/ruby/2.6.0/rubygems/requirement.rb:135:in `map!'
45
  /usr/local/lib/ruby/2.6.0/rubygems/requirement.rb:135:in `initialize'
46
  /usr/local/bundle/bundler/gems/dependabot-core-44f458dba8ce/terraform/lib/dependabot/terraform/requirement.rb:27:in `new'
47
  /usr/local/bundle/bundler/gems/dependabot-core-44f458dba8ce/terraform/lib/dependabot/terraform/requirement.rb:27:in `requirements_array'
48
  /usr/local/bundle/bundler/gems/dependabot-core-44f458dba8ce/common/lib/dependabot/update_checkers/base.rb:267:in `block in version_from_requirements'
49
  /usr/local/bundle/bundler/gems/dependabot-core-44f458dba8ce/common/lib/dependabot/update_checkers/base.rb:267:in `each'
50
  /usr/local/bundle/bundler/gems/dependabot-core-44f458dba8ce/common/lib/dependabot/update_checkers/base.rb:267:in `flat_map'
51
  /usr/local/bundle/bundler/gems/dependabot-core-44f458dba8ce/common/lib/dependabot/update_checkers/base.rb:267:in `version_from_requirements'
52
  /usr/local/bundle/bundler/gems/dependabot-core-44f458dba8ce/common/lib/dependabot/update_checkers/base.rb:255:in `can_compare_requirements?'
53
  /usr/local/bundle/bundler/gems/dependabot-core-44f458dba8ce/common/lib/dependabot/update_checkers/base.rb:246:in `requirements_up_to_date?'
54
  /usr/local/bundle/bundler/gems/dependabot-core-44f458dba8ce/common/lib/dependabot/update_checkers/base.rb:29:in `up_to_date?'
55
  /usr/src/app/dependabot.rb:103:in `block in update'
56
  /usr/src/app/dependabot.rb:93:in `each'
57
  /usr/src/app/dependabot.rb:93:in `update'
58
  /usr/src/app/dependabot.rb:162:in `block in <top (required)>'
59
  /usr/src/app/dependabot.rb:153:in `each'
60
  /usr/src/app/dependabot.rb:153:in `<top (required)>'
Complete job
```

**Comment by patrickjahns** [comment]
Thanks for your remark. 

As the github action is "just a wrapper" around dependabot itself - I suggest to open the issue upstream https://github.com/dependabot/dependabot-core

It would be best to address this upstream and ideally get https://github.com/dependabot/dependabot-core/pull/1388 also merged
